### ISSUE TITLE
Potlatch 3: line pattern degradation

### ISSUE THREAD

**Issue by zstadler** [systemed/potlatch2#140] opened 2020-12-22 15:18 UTC
There is some sort of visual degradation of the line patterns in Potlatch 3.

![image](https://user-images.githubusercontent.com/1304610/102902892-391e8d80-4478-11eb-8c67-005e72464e9b.png)

Potlatch 3 is on the left and Potlatch 2 the right.

![image](https://user-images.githubusercontent.com/1304610/102903457-0a54e700-4479-11eb-9fd5-46e079b0c8e6.png)  ![image](https://user-images.githubusercontent.com/1304610/102903752-70416e80-4479-11eb-8c79-dff48f40fa5f.png)

A section in zoom 19

Perhaps this is a side effect of some difference in precision indroduced in Potlatch 3.

**Comment by systemed** [comment] 2020-12-22 15:38
It's a bit complex. Effectively Potlatch fixes its coordinate system around the place you start editing, and due to limitations in Flash's floating point arithmetic, the drawing becomes less accurate the further away from there that you get.

In P2 this isn't really an issue because you will typically navigate to the place you want to edit using the slippy map on osm.org, then click Edit, at which point P2 will launch and fix its coordinate system around that location. (But you can recreate this effect in P2 by launching at one location, then using the search button to move to the other side of the world.)

In P3, the navigation is largely done within P3 itself, so it has a bunch of new code to work out the best place to fix the coordinate system. If, for example, I launch P3, click the search button, type "Charlbury", and select the first item on the list, then it'll fix its coordinate system there and drawing will be fine.

But this is new code and it's very possible that there are issues with it. So if you have a steps to reproduce the issue, that'd be great - I can then look at how to fix them.

**Comment by zstadler** [comment] 2020-12-22 19:38
Thanks @systemed for the technical background. I assume this also impacts the maximal zoom level beyond which OSM elements are no longer visible.

The first user flow I'm using is
1. Open P3, with OSM  standard map as the background
2. Pan and zoom to the area of interest
3. Start editing as soon as the OSM elements are visible

In this scenario, it would be reasonable, IMHO, to set fix the coordinate system at the location of the first download of OSM elements. BTW, I would prefer increasing the minimal zoom level at which OSM elements are visible if this would enable editing in higher zoom levels.

The other scenario I was using in P2 is to use the "edit" link of one of the GPS recordings I've uploaded to OSM. In this flow, the initial location is set to the start if the trace.
Perhaps P3 could use the location of the GPS trace to fix the coordinate system, if not already set. Zooming to the start of the trace at zoom=16, as done in P2, would also be a beneficial UX, IMHO.

Other options to consider for P3:
- Use the positon of the previous exit as the next start point
- Add a "Start" bookmark

**Comment by systemed** [comment] 2020-12-22 19:58
> it would be reasonable, IMHO, to set fix the coordinate system at the location of the first download of OSM elements.

It's meant to do that. If you can expand on how you're accomplishing step 2 that'd help me to pin down why it's not doing so in this scenario.

**Comment by zstadler** [comment] 2020-12-22 21:28
Here is a series of screenshots. Fron the initial P3 screen, through mouse pans and clicks on the "+" button, to the above view.
Please let me know if there is a better way to secribe step 2 above.

The final destination, for your reference is [Hemet Cistern](https://www.openstreetmap.org/node/4055251091).


![2020-12-22 23_15_43-Potlatch](https://user-images.githubusercontent.com/1304610/102934146-4e151400-44ac-11eb-91c3-63efb687a341.png)
![2020-12-22 23_15_50-Potlatch](https://user-images.githubusercontent.com/1304610/102934150-4fded780-44ac-11eb-8be5-1883c3e40c1f.png)
![2020-12-22 23_15_55-Potlatch](https://user-images.githubusercontent.com/1304610/102934154-51a89b00-44ac-11eb-86d2-248c9dc9a548.png)
![2020-12-22 23_16_02-Potlatch](https://user-images.githubusercontent.com/1304610/102934158-53725e80-44ac-11eb-8aca-f0c0443c77fe.png)
![2020-12-22 23_16_08-Potlatch](https://user-images.githubusercontent.com/1304610/102934161-553c2200-44ac-11eb-8d83-55c333dda128.png)
![2020-12-22 23_16_12-Potlatch](https://user-images.githubusercontent.com/1304610/102934163-5705e580-44ac-11eb-90d9-6eecdb4f0924.png)
![2020-12-22 23_16_17-Potlatch](https://user-images.githubusercontent.com/1304610/102934167-58cfa900-44ac-11eb-9181-c2c7e5855280.png)
![2020-12-22 23_16_23-Potlatch](https://user-images.githubusercontent.com/1304610/102934171-5a00d600-44ac-11eb-8557-847bed7cded3.png)
![2020-12-22 23_16_34-Potlatch](https://user-images.githubusercontent.com/1304610/102934176-5c633000-44ac-11eb-980f-3528a9dabf6d.png)
![2020-12-22 23_16_42-Potlatch](https://user-images.githubusercontent.com/1304610/102934178-5d945d00-44ac-11eb-9db9-99267329df42.png)
![2020-12-22 23_16_48-Potlatch](https://user-images.githubusercontent.com/1304610/102934183-5ec58a00-44ac-11eb-9ab3-c8cc325880ae.png)
![2020-12-22 23_16_52-Potlatch](https://user-images.githubusercontent.com/1304610/102934185-5ff6b700-44ac-11eb-8cd5-e2c143bfbf8d.png)
![2020-12-22 23_16_56-Potlatch](https://user-images.githubusercontent.com/1304610/102934191-61c07a80-44ac-11eb-967b-da81a30d1f3e.png)
![2020-12-22 23_17_03-Potlatch](https://user-images.githubusercontent.com/1304610/102934192-62591100-44ac-11eb-8849-3829b18a049d.png)
![2020-12-22 23_17_09-Potlatch](https://user-images.githubusercontent.com/1304610/102934201-638a3e00-44ac-11eb-89de-3f9cd2e8cc6d.png)
![2020-12-22 23_17_16-Potlatch](https://user-images.githubusercontent.com/1304610/102934204-64bb6b00-44ac-11eb-828c-525314d9b41e.png)
![2020-12-22 23_17_26-Potlatch](https://user-images.githubusercontent.com/1304610/102934209-65ec9800-44ac-11eb-9be7-6cee4c2b09c3.png)
![2020-12-22 23_17_33-Potlatch](https://user-images.githubusercontent.com/1304610/102934211-66852e80-44ac-11eb-945f-a382011a61db.png)
![2020-12-22 23_17_40-Potlatch](https://user-images.githubusercontent.com/1304610/102934218-67b65b80-44ac-11eb-907c-e03f3f56ec92.png)
![2020-12-22 23_17_47-Potlatch](https://user-images.githubusercontent.com/1304610/102934221-68e78880-44ac-11eb-8ca2-4d58f050c0c9.png)
![2020-12-22 23_17_53-Potlatch](https://user-images.githubusercontent.com/1304610/102934227-6a18b580-44ac-11eb-8e16-8ff4a48ba36d.png)
![2020-12-22 23_18_03-Potlatch](https://user-images.githubusercontent.com/1304610/102934229-6b49e280-44ac-11eb-86bd-7c6dc3ab0d22.png)
![2020-12-22 23_18_08-Potlatch](https://user-images.githubusercontent.com/1304610/102934234-6d13a600-44ac-11eb-86e9-ade05dae6f92.png)
![2020-12-22 23_18_12-Potlatch](https://user-images.githubusercontent.com/1304610/102934238-6dac3c80-44ac-11eb-972a-04d364ab75fd.png)
![2020-12-22 23_18_17-Potlatch](https://user-images.githubusercontent.com/1304610/102934246-6f760000-44ac-11eb-9710-eec07a1b2876.png)
![2020-12-22 23_18_21-Potlatch](https://user-images.githubusercontent.com/1304610/102934251-700e9680-44ac-11eb-87fa-79b927e8d6af.png)

**Comment by systemed** [comment] 2020-12-22 22:10
That's great - thanks. I'll look into it.

**Comment by systemed** [comment] 2020-12-28 15:32
Fixed in https://github.com/systemed/potlatch3/commit/b258e5eae316fee19ccbbe6490ed849331668981.

**Closed by systemed** 2020-12-28 15:32 UTC
